GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "i have a girlfriend"
}

###
DELETE http://localhost:3001/todo/delete/6539179647d9d404749a4797

###
GET http://localhost:3001/todo/complete/6539179647d9d404749a4797